version: "3.7"

services:
	db:
		image: mysql:8.0.17
                container_name: SmaIT-mysql
                ports:
                        - "3306:3306" # 접근 포트 설정
                environment:
                        - MYSQL_ROOT_PASSWORD=1234
                        - TZ=Asia/Seoul
                restart: unless-stopped
                command:
                        - --character-set-server=utf8mb4
                        - --collation-server=utf8mb4_unicode_ci
                volumes:
                        - /usr/shared/data/SmaIT-mysql:/var/lib/mysql
                networks: 
                        - smait
        jenkins:
                image: 'jenkinsci/jenkins'
                restart: unless-stopped
                user: root
                privileged: true
                ports: 
                        - '9090:8080'
                volumes:
                        - '/home/ubuntu/docker/jenkins-data:/var/jenkins_home'
                        - '/var/run/docker.sock:/var/run/docker.sock'
                        - '/usr/bin/docker:/usr/bin/docker'
                container_name: 'jenkins'
                environment:
                        - TZ=Asia/Seoul
networks: 
        smait:
                external: true